version: '3.8'
services:
  app:
    build: ./docker
    volumes:
      - ./crm:/var/www/crm-app
    working_dir: /var/www/crm-app
  nginx:
    image: nginx 
    ports:
      - 8083:80 
    volumes:
      - ./crm:/var/www/crm-app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    build: ./docker/db
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - crm:/var/lib/mysql
volumes:
  crm:
    driver: local